---

# Build step ensures that repository is correctly configured and won't fail on service removal or deployment

kind: pipeline
type: docker
name: build

trigger:
  branches:
  - deployment-test
  event:
    include:
    - custom
    - push
    exclude:
    - promote
    - rollback

volumes:
  - name: socket
    host:
      path: /var/run/docker.sock

steps:
  # Deploy services and then remove them in an isolated environment
  - name: build
    image: docker
    volumes:
    - name: socket
      path: /var/run/docker.sock
    commands:
      - docker compose up -d
      - docker compose down

---

# Deployment step performs the remote deployment to our central hosting instance

kind: pipeline
type: docker
name: deploy

trigger:
  branches:
  - master
  event:
    include:
    - promote
    - rollback
    exclude:
    - custom
    - push

clone:
  disable: true

steps:
  # Ensure the repo exists
  - name: clone
    image: appleboy/drone-ssh
    settings:
      host:
        - 212.71.250.173
      username: cameron
      key:
        from_secret: ssh_key
      script_stop: false
      script: |
        cd ~/repos
        if [ ! -d "${DRONE_REPO_NAME}" ]; then
          git clone http://cam:"p2Q=Z)uqWKN%t:F"@git.arg.tech/Projects/${DRONE_REPO_NAME}
        fi
  
  # Remove services if they are running
  - name: down
    image: appleboy/drone-ssh
    settings:
      host:
        - 212.71.250.173
      username: cameron
      key:
        from_secret: ssh_key
      script_stop: false
      script: |
        cd ~/repos/${DRONE_REPO_NAME}
        docker-compose down

  # Pull new changes from remote
  - name: pull
    image: appleboy/drone-ssh
    settings:
      host:
        - 212.71.250.173
      username: cameron
      key:
        from_secret: ssh_key
      script_stop: false
      script: |
        cd ~/repos/${DRONE_REPO_NAME}
        git pull

  # Deploy the services from commit
  - name: up
    image: appleboy/drone-ssh
    settings:
      host:
        - 212.71.250.173
      username: cameron
      key:
        from_secret: ssh_key
      script_stop: false
      script: |
        cd ~/repos/${DRONE_REPO_NAME}
        git reset --hard ${DRONE_COMMIT}
        git clean -df
        docker-compose up -d

---

kind: secret
name: ssh_key
get:
  path: kv/data/ssh/key
  name: deploy
