version: "3"
services:
  dozzle:
    build:
      context: ./dozzle
      args:
        admin_password: "${ADMIN_PASSWORD:?Not found in .env}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_NO_ANALYTICS: true
