name: "dozzle-log-streamer"

services:
  dozzle:
    container_name: "dozzle-log-streamer_dozzle"
    build: ./dozzle
    command: >
      sh -c '
      cat "$$ADMIN_PASSWORD_FILE" | tr -d "\n" | sha256sum | cut -f1 -d" " > /tmp/admin-hash &&
      sed -i "s/admin-password-hash-placeholder/$$(cat /tmp/admin-hash)/" /data/users.yml &&
      /dozzle
      '
    restart: unless-stopped
    ports:
      - "9999:8080"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_NO_ANALYTICS: true
      ADMIN_PASSWORD_FILE: /run/secrets/admin-password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - admin-password

secrets:
  admin-password:
    file: ./.secrets/admin-password.txt
