name: Deploy
on:
  push:
    branches: [main, master]
  pull_request:
      branches: ['*']

jobs:
  deploy:
    name: Deploy to environment
    uses: arg-tech/deploy-templates/.github/workflows/default-deploy-template.yml@main
    secrets: inherit
    with: 
      target_production_server_nickname: primary
