name: Deploy
on:
  push:
    branches: main
  pull_request:
      branches: ['*']
  pull_request_target:
      types: closed

jobs:
  deploy:
    name: Deploy to environment
    uses: arg-tech/deploy-templates/.github/workflows/default-deploy-template.yml@main
    secrets: inherit
    with: 
      target_production_server_nickname: primary
