name: CI
on: [push, pull_request]
jobs:
  deploy:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/deployment-test'
    steps:
      - name: Clone the repository
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script_stop: false
          script: |
            cd ~/repos
            if [ ! -d "${{ github.event.repository.name }}" ]; then
              git clone https://github.com/arg-tech/${{ github.event.repository.name }}.git
            fi
